// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <AVFoundation/AVFoundation.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) launch;

@end

@interface BaseQRViewController: UIViewController

@property IBOutlet UILabel * messageLabel;

-(IBAction) viewDidLoad;
-(IBAction) setup_elements;
-(IBAction) scanAction:(id) id;

@end

